server:
  port: 8090

web:
  upload-path: ~/temp/

spring:
  profiles:
    active: dev
  application:
    name: myScanner
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
    default-property-inclusion: non_null
    resources:
      static-locations: classpath:/META-INF/resources/,classpath:/resources/,classpath:/static/,classpath:/public/,file:${web.upload-path}

# spring boot mybatis 自动配置
mybatis:
  mapper-locations: classpath*:mappers/*.xml
  type-aliases-package: top.retnull.myscanner.entities
mapper:
  identity: MYSQL
  mappers: top.retnull.myscanner.common.BaseMapper
  not-empty: false
pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql

logging:
  level:
    top.retnull.myscanner.mapper: debug

# JWT 认证配置
jwt:
  tokenHeader: Authorization   #请求头
  expiration: 120                #单位(分钟),这里默认2小时
  tokenHead: "Bearer "
  sso: false                    #单点登录，是否开启

info:
  app:
    name: ${spring.application.name}
    description: myScanner
    version: 1.0

management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: ALWAYS

