spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/myscanner?useUnicode=true&characterEncoding=UTF8&useSSL=false&serverTimezone=GMT%2B8
    username: root
    password: xLY1999110
    platform: mysql
    type: com.zaxxer.hikari.HikariDataSource

  redis:
    database: 0
    host: localhost
    port: 6379
    timeout: 2000
    password: xLY1999110
    lettuce:
      pool:
        max-idle: 8
        min-idle: 0
        max-active: 8
        max-wait: -1ms
  cache:
    redis:
      use-key-prefix: true
      time-to-live: 60s




knife4j:
  # 开启增强配置
  enable: true
  # 开启生产环境屏蔽
  production: true
